### ISSUE TITLE
Logging Alert plugin not working on 4.3.9

### ISSUE THREAD

**Issue by Sinagot** [airbus-cyber/graylog-plugin-alert-wizard#111] opened 2023-02-02 13:16 UTC
Logging Alert plugin packaged with Wizard 4.4.1 is not working properly on a Graylog 4.3.9 fresh install (CentOS7).
When I click on "Notification", I can see the list of notifications, but if I click on one of them, I can't see any setting of the selected notification. It acts as if the plugin was not installed. Therefore, the plugin is seen as installed in the node settings.
Tried with Graylog 4.3.8 and 4.3.7, same issue.

**Comment by frantz45** [comment] 2023-02-10 09:23
I've just tested on a fresh CentOS 7 install and it's working fine. My environment:
- Graylog v4.3.9
- Wizard v4.4.1
- MongoDB v4.4.18
- ElasticSearch OSS v7.10.2
- Java 8 (OpenJDK)
- CentOS v7.9.2009
- Firefox ESR 102.6.0

**Comment by frantz45** [comment] 2023-03-06 16:54
I close this issue as I'm not able to reproduce it

**Closed by frantz45** 2023-03-06 16:54 UTC
