### ISSUE TITLE
Creation alert severity null/disabled

### ISSUE THREAD

**Issue by HGCH81** [airbus-cyber/graylog-plugin-alert-wizard#98] opened 2022-10-21 08:24 UTC
Hello, 

I'm trying using plugin in version 3.3.16, but when i trying creating new alert i  have a bug/misconfig in severity box.

this one is disable with any value. 

![image](https://user-images.githubusercontent.com/59529839/197149148-711d425b-4a85-4c7f-8c7c-c986db4e742b.png)

thx

**Comment by frantz45** [comment] 2022-10-21 12:32
Hello,
Which version of the plugin are you using ?
With Graylog v3.3.16 you need Wizard v3.3.X (v3.3.1 is the latest).
Check the compatibility array on the readme page:
<html>
<body>


Wizard Plugin Version | Graylog Version
-- | --
4.4.x | 4.3.x
4.3.x | 4.2.x
4.2.x | 4.2.x
4.1.x | 4.2.x
4.0.x | 4.1.x
3.3.x | 3.3.x
3.2.x | 3.2.x
3.1.x | 3.0.x
3.0.x | 3.0.x
2.0.x | 2.5.x
1.1.x | 2.5.x
1.0.0 | 2.4.x


</body>
</html>

**Comment by HGCH81** [comment] 2022-10-21 12:55
Hi,

Version 3.3.0 
graylog-plugin-alert-wizard-3.3.0.jar

i see new release 3.3.1 but same issue.

No log errors in form visualisation 
but i can't save my rule

2022-10-21 14:54:30,554 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.IllegalArgumentException: No enum constant com.airbus_cyber_security.graylog.events.config.SeverityType.

Thx

**Comment by frantz45** [comment] 2022-10-21 12:57
It's really strange, I've never encounter this issue.
Did you try to restart the Graylog service ? (And close your browser to avoir cache issue)
What is your web browser (and which version) ?

**Comment by HGCH81** [comment] 2022-10-24 08:08
i'm using lastest version of chrome

i have analyse html code and in input i have "disabled" option with different classes in "div",

severetype box have different css style than other "select options"

![image](https://user-images.githubusercontent.com/59529839/197477668-16830680-2bf0-4692-a76b-4afd8479db86.png)

**Comment by HGCH81** [comment] 2022-10-24 08:10
i'm using docker with Dockerfile

`FROM graylog/graylog:3.3.16
USER root

ENV GRAYLOG_VERSION 3.3.16

RUN apt-get update;apt-get install -y wget procps
RUN mkdir -p /usr/share/graylog/data/{journal,log,plugin,config,contentpacks}; \
    chown graylog:graylog /usr/share/graylog/data/{journal,log,plugin,config,contentpacks}; \
    chown graylog:graylog $JAVA_HOME/bin/java

RUN wget -O /usr/share/graylog/plugin/graylog-plugin-alert-wizard-3.3.1.jar https://github.com/airbus-cyber/graylog-plugin-alert-wizard/releases/download/3.3.1/graylog-plugin-alert-wizard-3.3.1.jar
RUN wget -O /usr/share/graylog/plugin/graylog-plugin-aggregation-count-2.2.0.jar  https://github.com/airbus-cyber/graylog-plugin-aggregation-count/releases/download/2.2.0/graylog-plugin-aggregation-count-2.2.0.jar
RUN wget -O /usr/share/graylog/plugin/graylog-plugin-correlation-count-2.2.0.jar https://github.com/airbus-cyber/graylog-plugin-correlation-count/releases/download/2.2.0/graylog-plugin-correlation-count-2.2.0.jar

USER graylog
ENTRYPOINT []
CMD ["/docker-entrypoint.sh"]`

**Comment by c8y3** [comment] 2022-11-21 12:09
Unfortunately, I was not able to reproduce your problem. I had no problem creating a new alert with the graylog generated from your Dockerfile.

As a side-note, it seems to me, the following commands in the Dockerfile should not be necessary:
RUN wget -O /usr/share/graylog/plugin/graylog-plugin-aggregation-count-2.2.0.jar https://github.com/airbus-cyber/graylog-plugin-aggregation-count/releases/download/2.2.0/graylog-plugin-aggregation-count-2.2.0.jar
RUN wget -O /usr/share/graylog/plugin/graylog-plugin-correlation-count-2.2.0.jar https://github.com/airbus-cyber/graylog-plugin-correlation-count/releases/download/2.2.0/graylog-plugin-correlation-count-2.2.0.jar

Because these plugins are already included in the alert wizard plugin 3.3.1. The plugin also contains plugin [Logging Alert Notification 2.2.0](https://github.com/airbus-cyber/graylog-plugin-logging-alert/releases/download/2.2.0/graylog-plugin-logging-alert-2.2.0.jar)

You can check which plugins are installed by looking at the node (System / Nodes). Section "Installed plugins" should display something like:
![graylog_installed_plugins](https://user-images.githubusercontent.com/25362953/203048188-3bd9fbd2-6a41-47c0-a9b1-3d400a91b397.png)

**Comment by frantz45** [comment] 2022-12-02 09:15
I close this issue as we weren't able to reproduce it.

**Closed by frantz45** 2022-12-02 09:15 UTC
